# Generated by Django 5.0.7 on 2024-08-17 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_revenue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='total_price',
        ),
    ]
