# Generated by Django 5.0.7 on 2024-08-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_remove_ticket_quantity_remove_ticket_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='keywords',
        ),
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.URLField(default=''),
        ),
    ]
