# Generated by Django 5.0.7 on 2024-08-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_remove_movie_keywords_movie_trailer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='revenue',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=12),
        ),
    ]
