# Generated by Django 5.0.7 on 2024-08-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_movie_vote_average'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='revenue',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='movie',
            name='vote_average',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=5),
        ),
    ]
