# Generated by Django 5.0.7 on 2024-08-26 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_userhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='screening',
            options={'ordering': ['date_time']},
        ),
        migrations.AlterUniqueTogether(
            name='screening',
            unique_together={('movie', 'cinema', 'date_time')},
        ),
    ]
