# Generated by Django 5.0.7 on 2024-08-27 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_alter_screening_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genres',
        ),
    ]
