# Generated by Django 5.0.7 on 2024-08-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('movies', '0005_remove_movie_keywords_movie_trailer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'ticket')},
        ),
    ]
